name: insurance_dbt
version: '1.0.0'
config-version: 2
profile: insurance_dbt

model-paths: ["models"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
test-paths: ["tests"]
macro-paths: ["macros"]
analysis-paths: ["analyses"]
docs-paths: ["docs_dbt"]

models:
  insurance_dbt:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: ephemeral
      +schema: intermediate
    marts:
      +schema: marts
      dimensions:
        +materialized: table
      facts:
        +materialized: incremental
      aggregates:
        +materialized: table

seeds:
  insurance_dbt:
    +quote_columns: false
    +schema: seed

snapshots:
  insurance_dbt:
    +schema: snapshots

tests:
  insurance_dbt:
    +severity: error

vars:
  insurance_dbt:
    default_start_date: '2020-01-01'
